services:
  user-service:
    build:
      context: ./user-management-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MYSQL_DATABASE: jdbc:mysql://mysql:3306/mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: rootpassword
      REDIS_HOST: redis
    depends_on:
         - mysql
         - redis

  task-service:
    build:
      context: ./task-management-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      MYSQL_DATABASE_URL: jdbc:mysql://mysql:3306/mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: rootpassword
      REDIS_HOST: redis
    depends_on:
        - mysql
        - redis


  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: rootpassword
      REDIS_HOST: redis
    ports:
       - "8082:8082"
    depends_on:
         - mysql
         - redis

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"

  redis:
    image: redis
    ports:
      - "6372:6379"










